# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tester.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ctester.proto\x12\x06mytest\"(\n\nNumberPair\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0cNumberResult\x12\r\n\x05value\x18\x01 \x01(\x05\"(\n\nStringPair\x12\x0c\n\x04str1\x18\x01 \x01(\t\x12\x0c\n\x04str2\x18\x02 \x01(\t\"\x1d\n\x0cStringResult\x12\r\n\x05value\x18\x01 \x01(\t2l\n\x06Tester\x12/\n\x03\x41\x64\x64\x12\x12.mytest.NumberPair\x1a\x14.mytest.NumberResult\x12\x31\n\x05Merge\x12\x12.mytest.StringPair\x1a\x14.mytest.StringResultb\x06proto3')

_NUMBERPAIR = DESCRIPTOR.message_types_by_name['NumberPair']
_NUMBERRESULT = DESCRIPTOR.message_types_by_name['NumberResult']
_STRINGPAIR = DESCRIPTOR.message_types_by_name['StringPair']
_STRINGRESULT = DESCRIPTOR.message_types_by_name['StringResult']
NumberPair = _reflection.GeneratedProtocolMessageType('NumberPair', (_message.Message,), {
    'DESCRIPTOR': _NUMBERPAIR,
    '__module__': 'tester_pb2'
    # @@protoc_insertion_point(class_scope:mytest.NumberPair)
})
_sym_db.RegisterMessage(NumberPair)

NumberResult = _reflection.GeneratedProtocolMessageType('NumberResult', (_message.Message,), {
    'DESCRIPTOR': _NUMBERRESULT,
    '__module__': 'tester_pb2'
    # @@protoc_insertion_point(class_scope:mytest.NumberResult)
})
_sym_db.RegisterMessage(NumberResult)

StringPair = _reflection.GeneratedProtocolMessageType('StringPair', (_message.Message,), {
    'DESCRIPTOR': _STRINGPAIR,
    '__module__': 'tester_pb2'
    # @@protoc_insertion_point(class_scope:mytest.StringPair)
})
_sym_db.RegisterMessage(StringPair)

StringResult = _reflection.GeneratedProtocolMessageType('StringResult', (_message.Message,), {
    'DESCRIPTOR': _STRINGRESULT,
    '__module__': 'tester_pb2'
    # @@protoc_insertion_point(class_scope:mytest.StringResult)
})
_sym_db.RegisterMessage(StringResult)

_TESTER = DESCRIPTOR.services_by_name['Tester']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _NUMBERPAIR._serialized_start = 24
    _NUMBERPAIR._serialized_end = 64
    _NUMBERRESULT._serialized_start = 66
    _NUMBERRESULT._serialized_end = 95
    _STRINGPAIR._serialized_start = 97
    _STRINGPAIR._serialized_end = 137
    _STRINGRESULT._serialized_start = 139
    _STRINGRESULT._serialized_end = 168
    _TESTER._serialized_start = 170
    _TESTER._serialized_end = 278
# @@protoc_insertion_point(module_scope)
